### ISSUE TITLE
draw functionality broken in phone use

### ISSUE THREAD

**Issue by katjaq** [r03ert0/microdraw#39]
drawing works great on computer, but in phone it creates new untitled regions but does not draw them on the slice; instead seems to jump to upper left corner of the screen and makes a dot there
also, it is hard to access the created regions in region list (they are off screen at bottom)
(tried on Google Nexus)

**Comment by r03ert0** [comment]
on ipad drawing works quite nicely, though. Probably, for small
screen-devices the priority should be to get data viewing right (only
extreme brain geeks will try to segment on their phones ;D)

**Comment by katjaq** [comment]
then maybe the menu bar shouldn't appear in small screen devices such as phone? as to give room to view the data...

**Comment by r03ert0** [comment]
in a first time, probably, the only tools for small screen devices should
be the prev and next slice button. Ideally, in the future, when the menuBar
is opened, it should occupy all the screen, so that the user can easily
select the tools/regions s/he wants to use, and then close the menuBar to
use them.
